### ISSUE TITLE
FizzBuzz Algorithm

### ISSUE THREAD

**Issue by Kim-Martino** [JW-s-project/fizzbuzz-team#1]
## 설명

if 와 for문을 활용한 fizzbuzz 알고리즘 구현 
- 숫자 범위 1~20 사이의 정수

## Tasks

- [x] : print 'fizz' times of 3
- [x] : print 'buzz' times of 5
- [x] : print 'fizzbuzz' times of 15
- [x] : print itself othercase

## Reference
- https://en.wikipedia.org/wiki/Fizz_buzz
